Repository Ayushsingh07/HELPERR, pull requests merged in 2022-10, with the labels that each got.

#1 Update sample.py
  PYTHON/sample.py
Labels: hacktoberfest

#2 Update sample.py
  PYTHON/sample.py
Labels: HACKTOBERFEST

#3 Random Password Generator
  C/C++/libraryManagement.cpp
  PYTHON/passwordGenerator.py
Labels: HACKTOBERFEST-ACCEPTED

#4 Update sample.py
  PYTHON/sample.py
Labels: HACKTOBERFEST-ACCEPTED

#7 Update passwordGenerator.py
  PYTHON/passwordGenerator.py
Labels: HACKTOBERFEST-ACCEPTED

#8 Create oddOrEven.py
  PYTHON/oddOrEven.py
Labels: HACKTOBERFEST-ACCEPTED

#9 Added neat one line Fizz Buzz example in python
  PYTHON/fizzbuzz-OneLiner.py
Labels: HACKTOBERFEST-ACCEPTED

#6 Update passwordGenerator.py
  PYTHON/passwordGenerator.py
Labels: HACKTOBERFEST-ACCEPTED

#11 Create prime or not.py
  PYTHON/prime or not.py
Labels: HACKTOBERFEST-ACCEPTED

#10 changed it
  PYTHON/sample.py
Labels: HACKTOBERFEST-ACCEPTED

#13 Updated Readme File
  README.md
Labels: HACKTOBERFEST-ACCEPTED

#16 PYTHON
  PYTHON/NLTK bot.py
  PYTHON/NUMPY.py
  PYTHON/OPENCV.py
  PYTHON/tic tac toe.py
Labels: HACKTOBERFEST-ACCEPTED

#15 Java _Ktor Server
  Java/ktor-sample1/.gitignore
  Java/ktor-sample1/build.gradle.kts
  Java/ktor-sample1/gradle.properties
  Java/ktor-sample1/gradle/wrapper/gradle-wrapper.jar
  Java/ktor-sample1/gradle/wrapper/gradle-wrapper.properties
  Java/ktor-sample1/gradlew
  Java/ktor-sample1/gradlew.bat
  Java/ktor-sample1/settings.gradle.kts
  Java/ktor-sample1/src/main/kotlin/com/example/Application.kt
  Java/ktor-sample1/src/main/kotlin/com/example/model/apiData.kt
  Java/ktor-sample1/src/main/kotlin/com/example/model/apiDataItem.kt
  Java/ktor-sample1/src/main/kotlin/com/example/plugins/Routing.kt
  Java/ktor-sample1/src/main/resources/application.conf
  Java/ktor-sample1/src/main/resources/logback.xml
  Java/ktor-sample1/src/test/kotlin/com/example/ApplicationTest.kt
Labels: HACKTOBERFEST-ACCEPTED

#14 Go version of FizzBuzz
  GO/fizzbuzz.go
Labels: HACKTOBERFEST-ACCEPTED

#17 opencv
  PYTHON/NUMPY (1).py
  PYTHON/OPENCV (1).py
  PYTHON/SETS.py
Labels: HACKTOBERFEST-ACCEPTED

#18 created model for a block of blockchain
  BlockChain/.gitignore
  BlockChain/BlockChain.iml
  BlockChain/src/Block.java
  BlockChain/src/BlockChain.java
  BlockChain/src/Main.java
Labels: HACKTOBERFEST-ACCEPTED

#19 Interface for api calls
  Java/ktor-sample1/src/main/kotlin/com/example/repository/ApiInterface.kt
Labels: HACKTOBERFEST-ACCEPTED

#20 python
  PYTHON/METHODS.py
Labels: HACKTOBERFEST-ACCEPTED

#21 Fix: Deleted and added few functions
  Java/ktor-sample1/src/main/kotlin/com/example/Application.kt
  Java/ktor-sample1/src/main/kotlin/com/example/constants/ConstantVariables.kt
  Java/ktor-sample1/src/main/kotlin/com/example/repository/ApiInterface.kt
Labels: HACKTOBERFEST-ACCEPTED

#22 Added a nft-preview-card-component project
  Web Development/NFT-preview-card-component/README.md
  Web Development/NFT-preview-card-component/design/active-states.jpg
  Web Development/NFT-preview-card-component/design/desktop-design.jpg
  Web Development/NFT-preview-card-component/design/desktop-preview.jpg
  Web Development/NFT-preview-card-component/design/mobile-design.jpg
  Web Development/NFT-preview-card-component/images/favicon-32x32.png
  Web Development/NFT-preview-card-component/images/icon-clock.svg
  Web Development/NFT-preview-card-component/images/icon-ethereum.svg
  Web Development/NFT-preview-card-component/images/icon-view.svg
  Web Development/NFT-preview-card-component/images/image-avatar.png
  Web Development/NFT-preview-card-component/images/image-equilibrium.jpg
  Web Development/NFT-preview-card-component/index.css
  Web Development/NFT-preview-card-component/index.html
Labels: HACKTOBERFEST-ACCEPTED

#24 Create Minimum Elements to Add to Form a Given Sum.py
  PYTHON/Minimum Elements to Add to Form a Given Sum.py
Labels: HACKTOBERFEST-ACCEPTED

#25 Refactored
  Java/ktor-sample1/src/main/kotlin/com/example/Application.kt
  Java/ktor-sample1/src/main/kotlin/com/example/model/apiData.kt
  Java/ktor-sample1/src/main/kotlin/com/example/repository/ApiInterface.kt
  Java/ktor-sample1/src/main/kotlin/com/example/repository/ApiInterfaceImplementation.kt
Labels: HACKTOBERFEST-ACCEPTED

#27 Revert "Refactored"
  Java/ktor-sample1/src/main/kotlin/com/example/Application.kt
  Java/ktor-sample1/src/main/kotlin/com/example/model/apiData.kt
  Java/ktor-sample1/src/main/kotlin/com/example/repository/ApiInterface.kt
  Java/ktor-sample1/src/main/kotlin/com/example/repository/ApiInterfaceImplementation.kt
Labels: HACKTOBERFEST-ACCEPTED

#28 added pose tracker
  PYTHON/PushupTracker/PoseTracker.py
Labels: HACKTOBERFEST-ACCEPTED

#29 added pushup counter
  PYTHON/PushupTracker/PushupCounter.py
Labels: HACKTOBERFEST-ACCEPTED

#30 added readme
  PYTHON/PushupTracker/README.md
Labels: HACKTOBERFEST-ACCEPTED

#31 added req.txt
  PYTHON/PushupTracker/requirements.txt
Labels: HACKTOBERFEST-ACCEPTED

#32 Created/Added Vehicle.cpp
  C/C++/Vehicle.cpp
Labels: HACKTOBERFEST-ACCEPTED

#34 update go files
  GO/WEBSERVER/main.go
  GO/WEBSERVER/static/form.html
  GO/WEBSERVER/static/index.html
Labels: HACKTOBERFEST-ACCEPTED

#35 added dijkstra.cpp in c++
  C/C++/dijkstra.cpp
Labels: HACKTOBERFEST-ACCEPTED

#36 Stone Paper Scissors
  PYTHON/stone_paper_scissors.py
Labels: HACKTOBERFEST-ACCEPTED

#37 color detection
  PYTHON/deteksiwarna.py
Labels: HACKTOBERFEST-ACCEPTED

#38 shape detection
  shape.py
Labels: HACKTOBERFEST-ACCEPTED

#40 Bubble Sort Algo
  C/C++/Bubble_Sort.cpp
Labels: HACKTOBERFEST-ACCEPTED

#41 adding a react-website
  Web Development/React-Marvel-App/.gitignore
  Web Development/React-Marvel-App/README.md
  Web Development/React-Marvel-App/package-lock.json
  Web Development/React-Marvel-App/package.json
  Web Development/React-Marvel-App/public/favicon.ico
  Web Development/React-Marvel-App/public/images/1.jpg
  Web Development/React-Marvel-App/public/images/10.jpg
  Web Development/React-Marvel-App/public/images/11.jpg
  Web Development/React-Marvel-App/public/images/12.jpg
  Web Development/React-Marvel-App/public/images/13.webp
  Web Development/React-Marvel-App/public/images/14.jpg
  Web Development/React-Marvel-App/public/images/15.jpg
  Web Development/React-Marvel-App/public/images/16.jpg
  Web Development/React-Marvel-App/public/images/17.jpeg
  Web Development/React-Marvel-App/public/images/18.jpg
  Web Development/React-Marvel-App/public/images/19.jpg
  Web Development/React-Marvel-App/public/images/2.jpeg
  Web Development/React-Marvel-App/public/images/20.jpg
  Web Development/React-Marvel-App/public/images/21.jpg
  Web Development/React-Marvel-App/public/images/22.webp
  Web Development/React-Marvel-App/public/images/23.webp
  Web Development/React-Marvel-App/public/images/24.jpg
  Web Development/React-Marvel-App/public/images/25.webp
  Web Development/React-Marvel-App/public/images/26.jpg
  Web Development/React-Marvel-App/public/images/27.jpeg
  Web Development/React-Marvel-App/public/images/28.webp
  Web Development/React-Marvel-App/public/images/29.jpg
  Web Development/React-Marvel-App/public/images/3.jpeg
  Web Development/React-Marvel-App/public/images/30.jpg
  Web Development/React-Marvel-App/public/images/31.jpeg
  Web Development/React-Marvel-App/public/images/32.webp
  Web Development/React-Marvel-App/public/images/33.webp
  Web Development/React-Marvel-App/public/images/34.webp
  Web Development/React-Marvel-App/public/images/35.jpg
  Web Development/React-Marvel-App/public/images/4.jpg
  Web Development/React-Marvel-App/public/images/5.jpg
  Web Development/React-Marvel-App/public/images/6.webp
  Web Development/React-Marvel-App/public/images/7.jpg
  Web Development/React-Marvel-App/public/images/8.jpg
  Web Development/React-Marvel-App/public/images/9.jpg
  Web Development/React-Marvel-App/public/index.html
  Web Development/React-Marvel-App/public/manifest.json
  Web Development/React-Marvel-App/public/robots.txt
  Web Development/React-Marvel-App/src/App.js
  Web Development/React-Marvel-App/src/components/basics/MovieCard.js
  Web Development/React-Marvel-App/src/components/basics/movieapi.js
  Web Development/React-Marvel-App/src/components/basics/movieapp.js
  Web Development/React-Marvel-App/src/components/basics/styles.css
  Web Development/React-Marvel-App/src/index.js
Labels: HACKTOBERFEST-ACCEPTED

#42 Merge branch 'main' of https://github.com/Ayushsingh07/HELPERR
  C/C++/insertionsort
  C/C++/insertionsort.cpp
Labels: HACKTOBERFEST-ACCEPTED

#44 Main
  .vscode/settings.json
  C/C++/mergesort
  C/C++/mergesort.cpp
Labels: HACKTOBERFEST-ACCEPTED

#45 Main
  C/C++/SelectionSort
  C/C++/SelectionSort.cpp
Labels: HACKTOBERFEST-ACCEPTED

#46 Main
  .vscode/settings.json
  C/C++/QuickSort
  C/C++/QuickSort.cpp
Labels: HACKTOBERFEST-ACCEPTED

#47 Main
  C/C++/DnfSort
  C/C++/DnfSort.cpp
Labels: HACKTOBERFEST-ACCEPTED

#48 tipcalculator
  JAVASCRIPT/tip.js
Labels: HACKTOBERFEST-ACCEPTED

#49 heapsort
  C/C++/heapsort.cpp
  JAVASCRIPT/tip.js
Labels: HACKTOBERFEST-ACCEPTED

#55 Update prime or not.py
  PYTHON/prime or not.py
Labels: HACKTOBERFEST-ACCEPTED

#54 Update stone_paper_scissors.py
  PYTHON/stone_paper_scissors.py
Labels: HACKTOBERFEST-ACCEPTED

#53 Update passwordGenerator.py
  PYTHON/passwordGenerator.py
Labels: HACKTOBERFEST-ACCEPTED

#52 Update oddOrEven.py
  PYTHON/oddOrEven.py
Labels: HACKTOBERFEST-ACCEPTED

#51 Update tic tac toe.py
  PYTHON/tic tac toe.py
Labels: HACKTOBERFEST-ACCEPTED

#65 Added floydWarshall.cpp
  C/C++/floydWarshall.cpp
Labels: HACKTOBERFEST-ACCEPTED

#64 Added Zig Zag Traversal
  C/C++/Zig_Zag_Traversal.cpp
Labels: HACKTOBERFEST-ACCEPTED

#63 Create n_queens.cpp
  C/C++/n_queens.cpp
Labels: HACKTOBERFEST-ACCEPTED

#61 Update NUMPY.py
  PYTHON/NUMPY.py
Labels: HACKTOBERFEST-ACCEPTED

#59 Update OPENCV.py
  PYTHON/OPENCV.py
Labels: HACKTOBERFEST-ACCEPTED

#57 Update SETS.py
  PYTHON/SETS.py
Labels: HACKTOBERFEST-ACCEPTED

#56 Update deteksiwarna.py
  PYTHON/deteksiwarna.py
Labels: HACKTOBERFEST-ACCEPTED

#58 Update fizzbuzz-OneLiner.py
  PYTHON/fizzbuzz-OneLiner.py
Labels: HACKTOBERFEST-ACCEPTED

#60 Update python folder
  PYTHON/IP address finder.py
  PYTHON/QR CODE GENERATOR.py
  PYTHON/QR scanner.py
  PYTHON/instagram progile pic downloader.py
  PYTHON/phonenumber.py
  PYTHON/screenshot with python.py
  PYTHON/security camera.py
  PYTHON/virtual assistant.py
  PYTHON/webscrapper.py
Labels: HACKTOBERFEST-ACCEPTED

#66 Added bellmanFord.cpp
  C/C++/bellmanFord.cpp
Labels: HACKTOBERFEST-ACCEPTED

#67 Radix Sort
  C/C++/radixSort.cpp
  PYTHON/rock_paper_scissors.py
Labels: HACKTOBERFEST-ACCEPTED

#70 Added Rock Paper Scissor Game
  Web Development/Rock_Paper_Scissor/app.js
  Web Development/Rock_Paper_Scissor/index.html
Labels: HACKTOBERFEST-ACCEPTED

#72 Car game
  racing-moto-game--main/bg.jpg
  racing-moto-game--main/blue.png
  racing-moto-game--main/index.html
  racing-moto-game--main/jumpsound.mp3
  racing-moto-game--main/main.js
  racing-moto-game--main/race.png
  racing-moto-game--main/style.css
Labels: HACKTOBERFEST-ACCEPTED

#73 Update app.js
  Web Development/Rock_Paper_Scissor/app.js
Labels: HACKTOBERFEST-ACCEPTED

#74 Program to send OTP through whatsapp
  JAVASCRIPT/otp.js
  JAVASCRIPT/sample.js
Labels: HACKTOBERFEST-ACCEPTED

#76 Multiplication of matrix
  C/C++/multiply.cpp
Labels: HACKTOBERFEST-ACCEPTED

#77 A single page webapp
  onepagewebsite/images/logo.png
  onepagewebsite/onepagewebsite.html
  onepagewebsite/style.css
Labels: HACKTOBERFEST-ACCEPTED

#78 Add Binary Tree questions
  C/C++/Binary Tree/Balanaced_binary_tree_O(n2).cpp
  C/C++/Binary Tree/Balanced_binary_tree_O(n).cpp
  C/C++/Binary Tree/Build_tree_by_post_and_inorder.cpp
  C/C++/Binary Tree/Build_tree_by_pre_and_inorder.cpp
Labels: HACKTOBERFEST-ACCEPTED

#82 Update style.css
  OPEN_FOR_ALL/NASA_startingpage/style.css
Labels: HACKTOBERFEST-ACCEPTED

#81 Update QR CODE GENERATOR.py
  PYTHON/QR CODE GENERATOR.py
Labels: HACKTOBERFEST-ACCEPTED

#80 Update otp.js
  JAVASCRIPT/otp.js
Labels: HACKTOBERFEST-ACCEPTED

#79 Update OPENCV (1).py
  PYTHON/OPENCV (1).py
Labels: HACKTOBERFEST-ACCEPTED

#89 Update screenshot with python.py
  PYTHON/screenshot with python.py
Labels: HACKTOBERFEST-ACCEPTED

#87 Add Graph part
  C/C++/Graph/bfs.cpp
  C/C++/Graph/dfs.cpp
Labels: HACKTOBERFEST-ACCEPTED

#86 Update stone_paper_scissors.py
  PYTHON/stone_paper_scissors.py
Labels: HACKTOBERFEST-ACCEPTED

#85 Update tic tac toe.py
  PYTHON/tic tac toe.py
Labels: HACKTOBERFEST-ACCEPTED

#84 Update virtual assistant.py
  PYTHON/virtual assistant.py
Labels: HACKTOBERFEST-ACCEPTED

#92 Created two.java
  Java/two.java
  Web Development/css-grid-challenge-1.html
Labels: HACKTOBERFEST-ACCEPTED

#91 create kadaneAlgo.cpp
  kadaneAlgo.cpp
Labels: HACKTOBERFEST-ACCEPTED

#90 Javascript game
  OPEN_FOR_ALL/math-addition-app-project-main/README.md
  OPEN_FOR_ALL/math-addition-app-project-main/app.js
  OPEN_FOR_ALL/math-addition-app-project-main/index.html
  OPEN_FOR_ALL/math-addition-app-project-main/style.css
Labels: HACKTOBERFEST-ACCEPTED

#93 created frm
  Web Development/index.html
Labels: HACKTOBERFEST-ACCEPTED

#96 Added To DO List Web App
  Web Development/To_DO_List/index.html
Labels: HACKTOBERFEST-ACCEPTED

#98 Created Sort_colors.java
  Java/Sort_colors.java
Labels: HACKTOBERFEST-ACCEPTED

#97 Added Find_in_Mountain_array.java File
  Java/Find_in_Mountain_array.java
Labels: HACKTOBERFEST-ACCEPTED

#106 Update NUMPY.py
  PYTHON/NUMPY.py
Labels: HACKTOBERFEST-ACCEPTED

#105 Update rock_paper_scissors.py
  PYTHON/rock_paper_scissors.py
Labels: HACKTOBERFEST-ACCEPTED

#103 Update security camera.py
  PYTHON/security camera.py
Labels: HACKTOBERFEST-ACCEPTED

#101 Update tic tac toe.py
  PYTHON/tic tac toe.py
Labels: HACKTOBERFEST-ACCEPTED

#102 Update stone_paper_scissors.py
  PYTHON/stone_paper_scissors.py
Labels: HACKTOBERFEST-ACCEPTED

#99 Update webscrapper.py
  PYTHON/webscrapper.py
Labels: HACKTOBERFEST-ACCEPTED

#107 Update NUMPY (1).py
  PYTHON/NUMPY (1).py
Labels: HACKTOBERFEST-ACCEPTED

#100 Update virtual assistant.py
  PYTHON/virtual assistant.py
Labels: HACKTOBERFEST-ACCEPTED

#108 Update phonenumber.py
  PYTHON/phonenumber.py
Labels: HACKTOBERFEST-ACCEPTED

#114 Step Counter
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/.gitignore
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/.idea/compiler.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/.idea/copyright/profiles_settings.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/.idea/encodings.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/.idea/gradle.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/.idea/misc.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/.idea/modules.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/.idea/scopes/scope_settings.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/.idea/vcs.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/LICENSE
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/README.md
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/StepCounter.iml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/build.gradle
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/gradle.properties
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/gradle/wrapper/gradle-wrapper.jar
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/gradle/wrapper/gradle-wrapper.properties
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/gradlew
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/gradlew.bat
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/settings.gradle
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/.gitignore
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/build.gradle
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/proguard-rules.txt
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/AndroidManifest.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/ic_launcher-web.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/java/com/paitoanderson/stepcounter/MainActivity.java
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/java/com/paitoanderson/stepcounter/data/Preferences.java
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/java/com/paitoanderson/stepcounter/receivers/BootReceiver.java
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/java/com/paitoanderson/stepcounter/receivers/NotificationReceiver.java
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/java/com/paitoanderson/stepcounter/services/StepCounter.java
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-hdpi/ic_launcher.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-hdpi/ic_stat_cancel.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-hdpi/ic_stat_feet.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-hdpi/ic_stat_reset.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-hdpi/ic_stat_share.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-mdpi/ic_launcher.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-mdpi/ic_stat_cancel.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-mdpi/ic_stat_feet.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-mdpi/ic_stat_reset.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-mdpi/ic_stat_share.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xhdpi/ic_launcher.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xhdpi/ic_stat_cancel.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xhdpi/ic_stat_feet.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xhdpi/ic_stat_reset.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xhdpi/ic_stat_share.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xxhdpi/ic_launcher.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xxhdpi/ic_stat_cancel.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xxhdpi/ic_stat_feet.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xxhdpi/ic_stat_reset.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/drawable-xxhdpi/ic_stat_share.png
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/src/main/res/values/strings.xml
  OPEN_FOR_ALL/StepCounter-master/StepCounter-master/stepcounter/stepcounter.iml
Labels: HACKTOBERFEST-ACCEPTED

#132 mask detection
  Web Development/mask detection system/Maskdetection2.jpeg
  Web Development/mask detection system/Maskdetection3.jpeg
  Web Development/mask detection system/Maskdetection4.jpg
  Web Development/mask detection system/dusra.html
  Web Development/mask detection system/maskdetection.html
  Web Development/mask detection system/maskdetection2.html
  Web Development/mask detection system/style.css
  Web Development/mask detection system/style2.css
  Web Development/mask detection system/stylemain.css
  Web Development/mask detection system/thankyou.html
Labels: HACKTOBERFEST-ACCEPTED

#131 Tic Tac Toe JS
  JAVASCRIPT/Tic Tac Toe JS/README.md
  JAVASCRIPT/Tic Tac Toe JS/css/game.css
  JAVASCRIPT/Tic Tac Toe JS/image/tic-tac-toe-js.gif
  JAVASCRIPT/Tic Tac Toe JS/index.html
  JAVASCRIPT/Tic Tac Toe JS/js/game.js
Labels: HACKTOBERFEST-ACCEPTED

#133 opencv mask detection
  PYTHON/app.py
  PYTHON/camera.py
Labels: HACKTOBERFEST-ACCEPTED

#134 error solved
  Web Development/Rock_Paper_Scissor/index.html
  Web Development/To_DO_List/index.html
Labels: HACKTOBERFEST-ACCEPTED

#135 Added Digital Clock in Python
  PYTHON/Digital_Clock.py
Labels: HACKTOBERFEST-ACCEPTED

#136 basic todo website code for beginner
  Web Development/Rock_Paper_Scissor/index.html
  Web Development/todo.html
Labels: HACKTOBERFEST-ACCEPTED

#138 Add Weather app
  Web Development/Weather App/Readme.md
  Web Development/Weather App/img/01n.svg
  Web Development/Weather App/img/04n.svg
  Web Development/Weather App/img/09n.svg
  Web Development/Weather App/img/50n.svg
  Web Development/Weather App/img/background_image.jpg
  Web Development/Weather App/img/haze.svg
  Web Development/Weather App/img/images.jpeg
  Web Development/Weather App/img/rain.svg
  Web Development/Weather App/img/storm.svg
  Web Development/Weather App/index.html
  Web Development/Weather App/script.js
  Web Development/Weather App/style.css
Labels: HACKTOBERFEST-ACCEPTED

#137 Sieve Of Eratosthenes
  Java/SieveOfEratosthenes.java
Labels: HACKTOBERFEST-ACCEPTED

#139 functions
  PYTHON/FUNCTIONS.py
Labels: HACKTOBERFEST-ACCEPTED

#140 functions1
  PYTHON/FUNCTIONS (1).py
Labels: HACKTOBERFEST-ACCEPTED

#142 add fetch subtitle from youtube
  PYTHON/fetch_subtitle_from_youtube/file.txt
  PYTHON/fetch_subtitle_from_youtube/main.py
Labels: HACKTOBERFEST-ACCEPTED

#143 Created Login
  Web Development/login2.css
  Web Development/login2.html
  Web Development/login2.js
Labels: HACKTOBERFEST-ACCEPTED

#144 created simple test doc
  Web Development/test/index.html
Labels: HACKTOBERFEST-ACCEPTED

#141 Created jokeGenerator.html
  Web Development/jokeGenerator.html
Labels: HACKTOBERFEST-ACCEPTED

#155 Added College Predictor Website
  Web Development/College PRediction system/Home.css
  Web Development/College PRediction system/Login.css
  Web Development/College PRediction system/Login.js
  Web Development/College PRediction system/README.md
  Web Development/College PRediction system/ScreenShots/is1.JPG
  Web Development/College PRediction system/ScreenShots/is2.JPG
  Web Development/College PRediction system/ScreenShots/is3.JPG
  Web Development/College PRediction system/ScreenShots/is4.JPG
  Web Development/College PRediction system/ScreenShots/is5.JPG
  Web Development/College PRediction system/home.php
  Web Development/College PRediction system/jagran_logo1.jpg
  Web Development/College PRediction system/login.php
  Web Development/College PRediction system/practice.css
  Web Development/College PRediction system/practice.php
  Web Development/College PRediction system/usertable.sql
Labels: HACKTOBERFEST-ACCEPTED

#154 Add files via upload
  PYTHON/mongoPython.py
Labels: HACKTOBERFEST-ACCEPTED

#153 update javascript folder
  JAVASCRIPT/github-card-with-reactjs-es6/dist/index.html
  JAVASCRIPT/github-card-with-reactjs-es6/dist/package.json
  JAVASCRIPT/github-card-with-reactjs-es6/dist/script.js
  JAVASCRIPT/github-card-with-reactjs-es6/dist/style.css
  JAVASCRIPT/github-card-with-reactjs-es6/dist/webpack.config.js
  JAVASCRIPT/github-card-with-reactjs-es6/src/script.babel
  JAVASCRIPT/github-card-with-reactjs-es6/src/style.scss
  JAVASCRIPT/image.png
Labels: HACKTOBERFEST-ACCEPTED

#152 Update screenshot with python.py
  PYTHON/screenshot with python.py
Labels: HACKTOBERFEST-ACCEPTED

#151 Update security camera.py
  PYTHON/security camera.py
Labels: HACKTOBERFEST-ACCEPTED

#149 Update tic tac toe.py
  PYTHON/tic tac toe.py
Labels: HACKTOBERFEST-ACCEPTED

#148 Update virtual assistant.py
  PYTHON/virtual assistant.py
Labels: HACKTOBERFEST-ACCEPTED

#147 Update webscrapper.py
  PYTHON/webscrapper.py
Labels: HACKTOBERFEST-ACCEPTED

#156 Added Netflix clone using vanilla Js , HTML , CSS
  netflix-master/README.md
  netflix-master/css/style.css
  netflix-master/img/background.jpg
  netflix-master/img/logo.png
  netflix-master/img/tab-content-1.png
  netflix-master/img/tab-content-2-1.png
  netflix-master/img/tab-content-2-2.png
  netflix-master/img/tab-content-2-3.png
  netflix-master/index.html
  netflix-master/js/main.js
Labels: HACKTOBERFEST-ACCEPTED

#168 Create SumOfDeepestLeaves.cpp
  C/C++/SumOfDeepestLeaves.cpp
Labels: HACKTOBERFEST-ACCEPTED

#167 Create MaximumDepthN-aryTree
  C/C++/MaximumDepthN-aryTree
Labels: HACKTOBERFEST-ACCEPTED

#166 Create N-aryTreePostorder.cpp
  C/C++/N-aryTreePostorder.cpp
Labels: HACKTOBERFEST-ACCEPTED

#165 Create LevelOrderTraversal.cpp
  C/C++/LevelOrderTraversal.cpp
Labels: HACKTOBERFEST-ACCEPTED

#164 Array Rotation
  C/C++/Array Rotation
Labels: HACKTOBERFEST-ACCEPTED

#178 Update rock_paper_scissors.py
  PYTHON/rock_paper_scissors.py
Labels: HACKTOBERFEST-ACCEPTED

#177 Update screenshot with python.py
  PYTHON/screenshot with python.py
Labels: HACKTOBERFEST-ACCEPTED

#162 Update mongoPython.py
  PYTHON/mongoPython.py
Labels: HACKTOBERFEST-ACCEPTED

#179 Create exfi-tool.py
  exfi-tool.py
Labels: HACKTOBERFEST-ACCEPTED

#182 some programs are added
  C/C++/binarysearch.cpp
  C/C++/binarysearch.exe
  C/C++/linearsearch.cpp
  C/C++/linearsearch.exe
  C/C++/maxmin.cpp
  C/C++/reversearray.cpp
  C/C++/reversearray.exe
Labels: HACKTOBERFEST-ACCEPTED

#184 factorial with recurssion program
  C/C++/factorialrecurssion.cpp
Labels: HACKTOBERFEST-ACCEPTED

#185 added few algo
  C/C++/Graph/Find_the_town_judge.cpp
  C/C++/Graph/Floyd-warshall-algo.cpp
  C/C++/Graph/KosarajuAlgo.cpp
  C/C++/Graph/Prims-algo.cpp
  C/C++/Graph/level_order.cpp
Labels: HACKTOBERFEST-ACCEPTED

#189 add mine sweeper game
  Java/Java-Minesweeper-Game-master/Java-Minesweeper-Game-master/README.md
  Java/Java-Minesweeper-Game-master/Java-Minesweeper-Game-master/bin/com/zetcode/Board$MinesAdapter.class
  Java/Java-Minesweeper-Game-master/Java-Minesweeper-Game-master/bin/com/zetcode/Board.class
  Java/Java-Minesweeper-Game-master/Java-Minesweeper-Game-master/bin/com/zetcode/Minesweeper.class
  Java/Java-Minesweeper-Game-master/Java-Minesweeper-Game-master/src/com/zetcode/Board.java
  Java/Java-Minesweeper-Game-master/Java-Minesweeper-Game-master/src/com/zetcode/Minesweeper.java
Labels: HACKTOBERFEST-ACCEPTED

#188 Created a linkedin bot
  PYTHON/linkedinbot.py
Labels: HACKTOBERFEST-ACCEPTED

#187 Different patterns in java
  Java/pattern1.java
  Java/pattern11.java
  Java/pattern14.java
  Java/pattern2.java
  Java/pattern3.java
  Java/pattern4.java
  Java/pattern7.java
  Java/pattern8.java
  Java/pattern9.java
Labels: HACKTOBERFEST-ACCEPTED

#183 Create Flloyd Warshal
  Java/Flloyd Warshal
Labels: HACKTOBERFEST-ACCEPTED

#191 Merge Sort Algorithm
  Java/Merge Sort Algorithm.java
  Java/Quicksort Algorithm.java
Labels: HACKTOBERFEST-ACCEPTED

#192 Update Digital_Clock.py
  PYTHON/Digital_Clock.py
Labels: HACKTOBERFEST-ACCEPTED

#193 Update NLTK bot.py
  PYTHON/NLTK bot.py
Labels: HACKTOBERFEST-ACCEPTED

#194 Update insertionsort.cpp
  C/C++/insertionsort.cpp
Labels: HACKTOBERFEST-ACCEPTED

#195 Update Bubble_Sort.cpp
  C/C++/Bubble_Sort.cpp
Labels: HACKTOBERFEST-ACCEPTED

#196 Dijkstra’s Algorithm
  Java/Breadth-First Search (BFS).java
  Java/Dijkstra’s Algorithm.java
Labels: HACKTOBERFEST-ACCEPTED

#198 some changes in algo
  Java/Breadth-First Search (BFS).java
  Java/Quicksort Algorithm.java
Labels: HACKTOBERFEST-ACCEPTED

#201 Bucket SOrt
  C/C++/SHellsort.cpp
  C/C++/bucketsort.cpp
  C/C++/countsort.cpp
Labels: HACKTOBERFEST-ACCEPTED

#202 Adding SOrt
  C/C++/radixsort.cpp
  C/C++/sortbyfrequency.cpp
Labels: HACKTOBERFEST-ACCEPTED

#214 Update Array Rotation
  C/C++/Array Rotation
Labels: HACKTOBERFEST-ACCEPTED

#213 Update METHODS.py
  PYTHON/METHODS.py
Labels: HACKTOBERFEST-ACCEPTED

#212 Update IP address finder.py
  PYTHON/IP address finder.py
Labels: HACKTOBERFEST-ACCEPTED

#211 Update Digital_Clock.py
  PYTHON/Digital_Clock.py
Labels: HACKTOBERFEST-ACCEPTED

#210 Update FUNCTIONS (1).py
  PYTHON/FUNCTIONS (1).py
Labels: HACKTOBERFEST-ACCEPTED

#215 Main
  C/C++/TargetSum_DP.cpp
  C/C++/climbingstairs_DP.cpp
Labels: HACKTOBERFEST-ACCEPTED

#216 Target SUm DP.
  C/C++/TargetSum_DP.cpp
Labels: HACKTOBERFEST-ACCEPTED

#217 Edit DIstance DP.
  C/C++/EditDIstance_DP.cpp
Labels: HACKTOBERFEST-ACCEPTED

#218 Trie Impelemtation.
  C/C++/TrieImplementation.cpp
Labels: HACKTOBERFEST-ACCEPTED

#220 Create c++
  C/C++/DFS/c++
Labels: HACKTOBERFEST-ACCEPTED

#219 Create Pattern 1 again
  Java/Pattern 1 again
Labels: HACKTOBERFEST-ACCEPTED
